# Generated by Django 6.0.6 on 2026-09-26 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_enabled', models.BooleanField(default=True, help_text='Controls whether citizens can access and submit the public feedback form.')),
                ('survey_offline_message', models.TextField(blank=True, default='Ang feedback system ay pansamantalang hindi available. Pakisubukan muli mamaya.', help_text='Notice shown to citizens when public feedback submissions are disabled.')),
                ('auto_analysis_enabled', models.BooleanField(default=True)),
                ('daily_summary_enabled', models.BooleanField(default=False)),
                ('notification_email', models.EmailField(blank=True, default='', max_length=254)),
                ('daily_summary_time', models.CharField(default='16:30', max_length=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'feedback configuration',
                'verbose_name_plural': 'feedback configuration',
            },
        ),
        migrations.CreateModel(
            name='FeedbackEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(choices=[('vsat', 'Very Satisfactory'), ('sat', 'Satisfactory'), ('unsat', 'Unsatisfactory')], max_length=25)),
                ('sentiment', models.CharField(choices=[('pos', 'Positive'), ('neu', 'Neutral'), ('neg', 'Negative'), ('pending', 'Pending'), ('na', 'N/A')], default='pending', max_length=10)),
                ('category', models.CharField(blank=True, choices=[('complaint', 'Complaint'), ('suggestion', 'Suggestion'), ('compliment', 'Compliment'), ('concern', 'Concern')], max_length=12)),
                ('comment', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='pending', max_length=12)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=50)),
                ('email_address', models.EmailField(blank=True, max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('client_type', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(blank=True, max_length=50)),
                ('name_of_client', models.CharField(blank=True, max_length=100)),
                ('staff_name', models.CharField(blank=True, help_text='Name of the staff member recorded at submission time', max_length=150)),
                ('services_availed', models.JSONField(blank=True, default=list)),
                ('cc1', models.CharField(blank=True, max_length=10)),
                ('cc2', models.CharField(blank=True, max_length=10)),
                ('cc3', models.CharField(blank=True, max_length=10)),
                ('sqd0', models.IntegerField(blank=True, null=True)),
                ('sqd1', models.IntegerField(blank=True, null=True)),
                ('sqd2', models.IntegerField(blank=True, null=True)),
                ('sqd3', models.IntegerField(blank=True, null=True)),
                ('sqd4', models.IntegerField(blank=True, null=True)),
                ('sqd5', models.IntegerField(blank=True, null=True)),
                ('sqd6', models.IntegerField(blank=True, null=True)),
                ('sqd7', models.IntegerField(blank=True, null=True)),
                ('sqd8', models.IntegerField(blank=True, null=True)),
                ('comments_suggestions', models.TextField(blank=True, max_length=1000)),
                ('commendation', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_assisted', models.ForeignKey(blank=True, help_text='Staff member who assisted the client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='feedback_fe_status_4a3328_idx'), models.Index(fields=['created_at'], name='feedback_fe_created_8be903_idx')],
            },
        ),
    ]
