# Generated by Django 6.0.6 on 2026-09-28 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedbackentry_ticket_number_feedbacktoken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacktoken',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='feedbackentry',
            name='token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedback.feedbacktoken'),
        ),
    ]
