# Generated by Django 6.0.6 on 2026-10-02 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_remove_feedbacktoken_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackentry',
            name='age',
        ),
        migrations.RemoveField(
            model_name='feedbackentry',
            name='cc1',
        ),
        migrations.RemoveField(
            model_name='feedbackentry',
            name='cc2',
        ),
        migrations.RemoveField(
            model_name='feedbackentry',
            name='cc3',
        ),
        migrations.RemoveField(
            model_name='feedbackentry',
            name='client_type',
        ),
        migrations.RemoveField(
            model_name='feedbackentry',
            name='commendation',
        ),
        migrations.RemoveField(
            model_name='feedbackentry',
            name='comments_suggestions',
        ),
        migrations.RemoveField(
            model_name='feedbackentry',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='feedbackentry',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='feedbackentry',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='feedbackentry',
            name='name_of_client',
        ),
        migrations.RemoveField(
            model_name='feedbackentry',
            name='services_availed',
        ),
        migrations.RemoveField(
            model_name='feedbackentry',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='feedbackentry',
            name='sqd0',
        ),
        migrations.RemoveField(
            model_name='feedbackentry',
            name='sqd1',
        ),
        migrations.RemoveField(
            model_name='feedbackentry',
            name='sqd2',
        ),
        migrations.RemoveField(
            model_name='feedbackentry',
            name='sqd3',
        ),
        migrations.RemoveField(
            model_name='feedbackentry',
            name='sqd4',
        ),
        migrations.RemoveField(
            model_name='feedbackentry',
            name='sqd5',
        ),
        migrations.RemoveField(
            model_name='feedbackentry',
            name='sqd6',
        ),
        migrations.RemoveField(
            model_name='feedbackentry',
            name='sqd7',
        ),
        migrations.RemoveField(
            model_name='feedbackentry',
            name='sqd8',
        ),
        migrations.RemoveField(
            model_name='feedbackentry',
            name='staff_assisted',
        ),
        migrations.RemoveField(
            model_name='feedbackentry',
            name='staff_name',
        ),
    ]
