# Generated by Django 6.0.6 on 2026-10-02 12:01

from django.db import migrations, models
from django.db.models import F


def copy_sentiment(apps, schema_editor):
    # Until now `sentiment` was read from the comment alone.
    apps.get_model('feedback', 'FeedbackEntry').objects.update(comment_sentiment=F('sentiment'))


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_drop_legacy_csm_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackentry',
            name='comment_sentiment',
            field=models.CharField(choices=[('pos', 'Positive'), ('neu', 'Neutral'), ('neg', 'Negative'), ('pending', 'Pending'), ('na', 'N/A')], default='pending', max_length=10),
        ),
        migrations.RunPython(copy_sentiment, migrations.RunPython.noop),
    ]
