# Generated by Django 6.0.6 on 2026-10-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_entry_comment_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackentry',
            name='topics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
