# Generated by Django 6.0.6 on 2026-10-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_entry_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackconfiguration',
            name='survey_enabled',
        ),
        migrations.RemoveField(
            model_name='feedbackconfiguration',
            name='survey_offline_message',
        ),
    ]
